### PR TITLE
Teams page Card UI Improvements

### PR DESCRIPTION
**Pull request by swastik-apk**
#108 UI of Cards in Team page updated.

This pull request includes several improvements to the `TeamsPage` components and updates to dependencies. The most important changes include the addition of the `simple-icons` package, refactoring of the `ContentTeamCard` and `TeamCard` components to use the new `SimpleIcon` component and improvement in th card UI, and the removal of the `icons` array from `PeopleData.js`.

### Dependency Updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R35): Added `simple-icons` package to dependencies.

### Component Refactoring:
* [`src/components/TeamsPage/ContentTeamCard/ContentTeamCard.jsx`](diffhunk://#diff-d2e5ca3796afb4ab5817ed938a5f9586c71e378096439f360978e62bbd47ec21R4-R51): Refactored to use the new `SimpleIcon` component for LinkedIn icons and improved the card's styling and structure.
* [`src/components/TeamsPage/TeamCard/TeamCard.jsx`](diffhunk://#diff-70c89d7bf72a87d26af58416688ad7aa04e41727810682789e078b698b322475L4-R61): Refactored to use the new `SimpleIcon` component for GitHub and LinkedIn icons and improved the card's styling and structure.

### Data Cleanup:
* [`src/data/TeamsPage/PeopleData.js`](diffhunk://#diff-c964bba500c5040bc44545fdbd5185c011394a1870449fa850182523ecfee31bL62-L74): Removed the `icons` array.

### CODE REVIEW

**Comment by Akangkha** [comment]
@swastik-apk  Hey. It's great to have you as a contributor. We would like to see a more detailed explanation of your work . A video or a picture will work great.

**Comment by swastik-apk** [comment]
https://github.com/user-attachments/assets/ed0e192e-7a2c-467e-bdb1-2633672ae933

@Akangkha video demo of the page

**Comment by swastik-apk** [comment]
Page_After

@Akangkha picture

**Comment by swastik-apk** [comment]
@Akangkha Can you elaborate on what type of card design do you expect ?

**Comment by Akangkha** [comment]
@swastik-apk You can replace those png with react-icons as its there among our packages. As for the UI , it's left upon the contributor's creativity. Try to have the dimension of the cards as you have modified , but you can give a more modern outlook to the UI.

**Comment by swastik-apk** [comment]
https://github.com/user-attachments/assets/5b5fd459-7927-4c04-81bd-2809393e741d

- I have updated the icons using "react-icons".
- Used framer-motion on the cards for that effect.
- Added color styling to the catchphrases.
@Akangkha

**Review by Akangkha — APPROVED** [review]

**Comment by Akangkha** [comment]
@swastik-apk  Hey reviewed the work. Your PR is accepted and will be merged under hactoberfest 2024.

**Pull request merged**
