### PR TITLE
Fix Image Stretching Issue in Homepage

### PR DESCRIPTION
**Pull request by swastik-apk**
#106 Fix Image Stretching Issue in "About Us" and "Behind the scenes" section of homepage

This pull request includes several updates to the `About`, and `BTS` components to improve the user interface and code quality. The most important changes include importing new icons for social media links, fixing a bug in the `handleClick` function, and updating the layout and styling of the `About` and `BTS` sections.

### About Component Updates:

* Refactored the `About` section to improve layout and responsiveness, including changes to the carousel and image components. (`src/components/homepage/About/About.jsx`)

### BTS Component Updates:

* Refactored the `BTS` section to improve layout and responsiveness, including changes to the carousel and image components. (`src/components/homepage/BTS/BTS.jsx`)

### Carousel Component Updates:

* Added an aspect ratio box to the carousel component to prevent image stretching and ensure consistent layout. (`src/components/ui/Carousel/Carousel.jsx`)

### CODE REVIEW

**Comment by swastik-apk** [comment]
This pull request also includes a minor update to the `Footer` component in `src/components/Footer/Footer.jsx`. The changes focus on improving the code readability, fixing minor bugs, and updating the icons used in the footer.

### Code readability improvements:
* Removed redundant `break` statements from the `switch` cases in the `handleClick` function.
* Refactored the scroll logic to ensure `scrollTo` is defined before attempting to scroll.

### Bug fixes:
* Corrected the layout of the "Go to Top" button to ensure proper alignment and spacing on mobile devices.

### Icon updates:
* Replaced `PNG Image` components with `react-icons` for social media links.\

image

**Comment by swastik-apk** [comment]
@JATIN0926 @Akangkha Pls review and merge the PR.

**Comment by Akangkha** [comment]
hey,can you show the Image stretch fix in a video format

**Comment by swastik-apk** [comment]
https://github.com/user-attachments/assets/8ee53e65-b3a5-43e2-878b-bf9d0389fde9

@Akangkha Proof of work

**Comment by swastik-apk** [comment]
@Akangkha Are you still there ?

**Review by Akangkha — APPROVED** [review]

**Comment by Akangkha** [comment]
I have reviewed the code and accepted the changes under hacktoberfest . Appreciate the efforts , keep contributing !

**Pull request merged**
