### PR TITLE
Minor: Footer UI Improvements

### PR DESCRIPTION
**Pull request by swastik-apk**
This pull request includes several updates to the `Footer` component in `src/components/Footer/Footer.jsx`. The changes focus on improving the code readability, fixing minor bugs, and updating the icons used in the footer.

### Code readability improvements:
* Removed redundant `break` statements from the `switch` cases in the `handleClick` function.
* Refactored the scroll logic to ensure `scrollTo` is defined before attempting to scroll.

### Bug fixes:
* Corrected the layout of the "Go to Top" button to ensure proper alignment and spacing on mobile devices.

### Icon updates:
* Replaced `PNG Image` components with `react-icons` for social media links.\

image

### CODE REVIEW

**Comment by Akangkha** [comment]
Hey, appreciate your contribution. Apart from this , we would encourage you to take up the issues listed in the repository. Choose any one of them and we can assign you that .

**Comment by swastik-apk** [comment]
@Akangkha So what happens to this PR ?

**Comment by Akangkha** [comment]
@swastik-apk you can add your new changes in this PR

**Comment by swastik-apk** [comment]
@Akangkha I have tried, but I cannot solve the other listed issues. Sorry for the inconvenience.

**Comment by Akangkha** [comment]
@swastik-apk Not an issue. Keep contributing and learning !

**Comment by swastik-apk** [comment]
@Akangkha  So what about this PR ?

**Comment by swastik-apk** [comment]
@Akangkha You can merge this PR without adding the hacktoberfest label. Make it a normal pr contribution.

**Pull request closed without merging**
