### PR TITLE
Search Bar Improvements in Community Page

### PR DESCRIPTION
**Pull request by Sanjeev-Kumar78**
#107 Search bar Responsiveness updated.

This pull request includes several updates to the `next.config.mjs`, `package.json`, and a CSS class in `CommunitySection.jsx`. The most important changes include the addition of a custom Webpack configuration, updates to dependencies, and a CSS class modification for responsive design.

### Webpack Configuration:
* [`next.config.mjs`](diffhunk://#diff-18c049b08c4a0f5ab451c598aeb2c4848bb9d7877b51ca3e5effb94a225814d2R21-R35): Added a custom Webpack configuration to include a Babel loader for the `undici` module when not on the server.

### Dependency Updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R13-R30): Added new dependencies `@babel/preset-env`, `@react-aria/interactions`, `babel-loader`, `prismjs`, and `undici`. Updated the `firebase` and `next` dependencies to newer versions. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R13-R30) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L35-R43)

### CSS Class Modification:
* [`src/components/communityPage/CommunitySection/CommunitySection.jsx`](diffhunk://#diff-6df45a914d5ac56ad087f504a6ea707177454d7db625ceb12cd912613bfa53e6L218-R218): Modified the CSS class of the search input to improve responsiveness across different screen sizes.

### CODE REVIEW

**Comment by Akangkha** [comment]
Thank you for the updates you've made so far . They’ve definitely improved the UI. However, we would appreciate it if you could make a few additional enhancements to further elevate the user experience before we accept the PR

**Comment by Akangkha** [comment]
@Sanjeev-Kumar78   The env variables are :
NEXT_PUBLIC_DIRECTUS_URL: "https://guidely.iotkiit.in/directus/"
TOKEN: "wMh03ug1LxGOdtQjAxyUZCny2yW9JKyj"
USER_ROLE: "22d0ebb3-a6e6-4ac9-ad1d-bf5cce44ea1d"
Rest are firebase creds.

**Comment by swastik-apk** [comment]
@Sanjeev-Kumar78 Can you share the process to bypass the login redirection ?

**Comment by Akangkha** [comment]
@Sanjeev-Kumar78  do say me the creds you used to login . I will update the access permission for the same

**Comment by swastik-apk** [comment]
> > @Sanjeev-Kumar78 Can you share the process to bypass the login redirection ?
> 
> Instead Use Environment Variables given above [#109 (comment)](https://github.com/iot-lab-kiit/intern-fair/pull/109#issuecomment-2409098658)

Can you guide me a bit more on this ?

**Comment by Akangkha** [comment]
@Sanjeev-Kumar78 updated the access permission . You can access the course pages now.

**Comment by Akangkha** [comment]
There might have been some misconfigurations from our side. I have updated the policies. Please do check now if you can access it.

**Comment by Akangkha** [comment]
Can you access the resources from the app using the token and user role ? @Sanjeev-Kumar78

**Review by Akangkha — APPROVED** [review]

**Comment by Akangkha** [comment]
Your code has been reviewed. Your PR  is accepted. Thank you for contributing to the repository.

**Pull request merged**
